#!/usr/bin/env python3
"""Build the case-study pages: work/<slug>.html.

Each page = the shared shell (head, icon sprite, sidebar, footer — taken
from index.html so there is one source of truth) + an article from
content/work/<slug>.html, described by content/work/projects.json.

    python3 scripts/build-case-studies.py

Re-run after editing index.html's sidebar/footer or anything under
content/work/, then commit the generated work/*.html. Stdlib only.
"""
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content" / "work"
OUT = ROOT / "work"
SITE = "https://nikolasneofytou.github.io/personal-website"


def between(text: str, start: str, end: str) -> str:
    """The slice from `start` up to and including the first `end` after it."""
    i = text.index(start)
    return text[i:text.index(end, i) + len(end)]


def relink(fragment: str) -> str:
    """Point index-relative links one directory up; in-page anchors go home."""
    def fix(m: re.Match) -> str:
        attr, url = m.group(1), m.group(2)
        if url.startswith("#i-"):                      # sprite references stay local
            return m.group(0)
        if url.startswith("#"):
            url = "../index.html" + (url if url != "#top" else "")
        elif not re.match(r"[a-z]+:|//|/", url):
            url = "../" + url
        return f'{attr}="{url}"'
    return re.sub(r'\b(href|src)="([^"]*)"', fix, fragment)


def main() -> None:
    index = (ROOT / "index.html").read_text()
    version = re.search(r'css/styles\.css\?v=([\w-]+)', index).group(1)
    sprite = between(index, "    <!-- Icon sprite", "</svg>\n")
    sidebar = relink(between(index, '<header class="sidebar"', "</header>"))
    sidebar = sidebar.replace('href="../index.html#work" class="nav-link"',
                              'href="../index.html#work" class="nav-link active" aria-current="page"')
    footer = between(index, '<footer class="site-footer">', "</footer>")

    projects = json.loads((CONTENT / "projects.json").read_text())
    OUT.mkdir(exist_ok=True)
    for i, p in enumerate(projects):
        nxt = projects[(i + 1) % len(projects)]
        body = (CONTENT / f"{p['slug']}.html").read_text().rstrip()
        e = {k: html.escape(str(v), quote=True) for k, v in p.items() if not isinstance(v, (list, dict))}
        meta = "\n".join(
            f'                        <div><dt>{html.escape(k)}</dt><dd>{v}</dd></div>' for k, v in p["meta"].items())
        url = f"{SITE}/work/{p['slug']}.html"
        demo_js = (f'\n    <script src="../js/explainers.js?v={version}" defer></script>'
                   if "data-demo=" in body else "")
        # badge: "Public"/"Private" by default; a project can override it (e.g. "Live")
        open_ = p["public"] or "flag" in p
        flag = html.escape(p.get("flag", "Public" if p["public"] else "Private"))
        page = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Generated by scripts/build-case-studies.py from content/work/ — edit there, not here. -->
    <title>{e['title']} — case study · Nikolas Neofytou</title>
    <meta name="description" content="{e['description']}">
    <meta name="author" content="Nikolas Neofytou">
    <meta name="theme-color" content="#F5F4EF">
    <link rel="canonical" href="{url}">
    <meta property="og:title" content="{e['title']} — case study · Nikolas Neofytou">
    <meta property="og:description" content="{e['description']}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{url}">
    <meta property="og:site_name" content="Nikolas Neofytou">
    <meta property="og:image" content="{SITE}/assets/og-image.jpg">
    <meta name="twitter:card" content="summary_large_image">
    <link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">
    <link rel="stylesheet" href="../css/styles.css?v={version}">
    <link rel="preload" href="../assets/fonts/instrument-serif.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="../assets/fonts/inter-var.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="../assets/covers/{e['slug']}-1344.webp" as="image" fetchpriority="high">
</head>
<body class="cs-page">
{sprite}
    <a class="skip-link" href="#content">Skip to content</a>

    <div class="layout">
        {sidebar}

        <main class="main" id="top">
            <article class="cs" id="content">
                <a class="cs-crumb" href="../index.html#work"><svg class="icon" aria-hidden="true" focusable="false"><use href="#i-chevron-left"></use></svg> Selected work</a>

                <header class="cs-head">
                    <p class="cs-kicker"><span class="section-num">{e['num']}</span> Case study <span class="case-flag{' case-flag--open' if open_ else ''}"><svg class="icon" aria-hidden="true" focusable="false"><use href="#i-{'unlock' if open_ else 'lock'}"></use></svg> {flag}</span></p>
                    <h1 class="cs-title" style="view-transition-name: title-{e['slug']}">{e['title']}</h1>
                    <p class="cs-lede">{p['lede']}</p>
                    <dl class="cs-meta">
{meta}
                    </dl>
                </header>

                <figure class="cs-hero">
                    <img src="../assets/covers/{e['slug']}-1344.webp" width="1344" height="752" alt="{e['alt']}"
                         style="view-transition-name: cover-{e['slug']}" fetchpriority="high" decoding="async">
                </figure>

{body}
            </article>

            <nav class="cs-next" aria-label="Next case study">
                <a href="{nxt['slug']}.html" class="cs-next-link">
                    <span class="cs-next-label">Next case study <svg class="icon" aria-hidden="true" focusable="false"><use href="#i-arrow-right"></use></svg></span>
                    <span class="cs-next-title">{html.escape(nxt['title'])}</span>
                    <span class="cs-next-lede">{html.escape(nxt['tagline'])}</span>
                </a>
            </nav>

            {footer}
        </main>
    </div>

    <button class="back-to-top" id="backToTop" aria-label="Back to top"><svg class="icon" aria-hidden="true" focusable="false"><use href="#i-arrow-up"></use></svg></button>
    <script src="../js/script.js?v={version}"></script>{demo_js}
</body>
</html>
"""
        (OUT / f"{p['slug']}.html").write_text(page)
        print(f"work/{p['slug']}.html")


if __name__ == "__main__":
    main()
